# Generated by Django 5.2.4 on 2025-07-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emailcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailaccount',
            name='uid',
            field=models.CharField(default='unknown', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
