# Generated by Django 5.2.4 on 2025-07-19 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gmailaccount_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('snippet', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('is_archived', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='api.emailcategory')),
                ('gmail_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='api.gmailaccount')),
            ],
        ),
    ]
