# Generated by Django 5.2.4 on 2025-07-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='wasReviewedByAI',
            field=models.BooleanField(default=False),
        ),
    ]
