# Generated by Django 5.2.4 on 2025-07-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_email_wasreviewedbyai'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailaccount',
            name='backlog_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='last_history_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='watch_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
